logging:
  level:
    kz:
      zhelezyaka: debug

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
  flyway:
    enabled: false
  data:
    rest:
      base-path: /api/v1