logging:
  level:
    kz:
      zhelezyaka: debug
#    org:
#      springframework:
#        security: trace

spring:
  flyway:
    enabled: false
  data:
    rest:
      base-path: /api/v1
  security:
    user:
      name: user1
      password: password

