spring:
  datasource:
    url: jdbc:mysql://172.20.0.1:3307/restdb?allowPublicKeyRetrieval=true&useSSL=false
    driverClassName: com.mysql.cj.jdbc.Driver
    username: restadmin
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
