spring:
  datasource:
    url: jdbc:mysql://172.21.0.1:3307/restdb?allowPublicKeyRetrieval=true&useSSL=false
    driverClassName: com.mysql.cj.jdbc.Driver
    username: restadmin
    password: password
    hikari:
      pool-name: RestDB-Pool
      maximum-pool-size: 5

  jpa:
    hibernate:
      ddl-auto: validate
    defer-datasource-initialization: false
    database: mysql
    properties:
#      jakarta:
#        persistence:
#          schema-generation:
#            scripts:
#              action: drop-and-create
#              create-source: metadata
#              drop-target: V1__init_mysql_database.sql
#              create-target: V1__init_mysql_database.sql
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.orm.jdbc.bind: trace
    kz:
      zhelezyaka: debug